### ISSUE TITLE
Decide on naming – posthog-plugins v. @posthog/plugin-scaffold v. something else?

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-scaffold#1]
The latest version of this package (0.2.5) is now published as `@posthog/plugin-scaffold` in npm. Previously it was `posthog-plugins` (which remains the repo name), but that is too confusing, as this is specifically only TypeScript scaffolding for plugins and the Node server (especially since we also have the `plugins` repo, which is a central directory of verified plugins).

We can deprecate `posthog-plugins` and
1. stick with `@posthog/plugin-scaffold`, or
2. move to something better and unpublish `@posthog/plugin-scaffold`.

Feedback needed and welcome.

**Comment by mariusandra** [comment]
I renamed this repo to `plugin-scaffold` to reflect the name of the package. However why not split the two code files into two: `@posthog/plugin-types` and `@posthog/plugin-test-utils` or something like that?

The `test/utils.js` file is used by the currency normailzation and helloworld plugins

**Comment by mariusandra** [comment]
Let's keep `@posthog/plugin-scaffold` for now and perhaps split into multiple projects when this expands in scope.
