### ISSUE TITLE
Rework plugin structure for autocompletion

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-scaffold#2]
The current way of building plugins offers no autocompletion, even though it's based on TypeScript. That's because we're exporting relevant functions at the top level. Instead, a plugin should `export default` an object implementing interface `Plugin` – this would offer much better guidance to plugin builders.

**Comment by mariusandra** [comment]
I'm not sure I agree with this. The consensus between JS folks seems to be to move away from default (nameless) exports.

In addition, unless you build plugins with a TS/babel step, you can't use `import`/`export` at all. Thus this will not help people using the inline plugin editor.

Can't the same be achieved with some `declarations.d.ts` file?

**Comment by Twixes** [comment]
Hm, will investigate how a declarations file would work (some time).
